# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_valueiteration_wrappers", use_symbols = TRUE, package_name = "valueiteration")

#' @docType package
#' @usage NULL
#' @useDynLib valueiteration, .registration = TRUE
NULL

value_iteration <- function(n, reward_guess, transition_flat, rows, cols, depth, beta, out) .Call(wrap__value_iteration, n, reward_guess, transition_flat, rows, cols, depth, beta, out)


# nolint end
